import { KanaChar } from "@/types";

export const HIRAGANA: KanaChar[] = [
  // A row
  { char: "あ", romaji: "a", row: "a", exampleWord: "あめ", exampleMeaning: "rain / candy" },
  { char: "い", romaji: "i", row: "a", exampleWord: "いぬ", exampleMeaning: "dog" },
  { char: "う", romaji: "u", row: "a", exampleWord: "うみ", exampleMeaning: "sea" },
  { char: "え", romaji: "e", row: "a", exampleWord: "えほん", exampleMeaning: "picture book" },
  { char: "お", romaji: "o", row: "a", exampleWord: "おに", exampleMeaning: "demon / ogre" },
  // K row
  { char: "か", romaji: "ka", row: "k", exampleWord: "かに", exampleMeaning: "crab" },
  { char: "き", romaji: "ki", row: "k", exampleWord: "きつね", exampleMeaning: "fox" },
  { char: "く", romaji: "ku", row: "k", exampleWord: "くも", exampleMeaning: "cloud / spider" },
  { char: "け", romaji: "ke", row: "k", exampleWord: "けむり", exampleMeaning: "smoke" },
  { char: "こ", romaji: "ko", row: "k", exampleWord: "こい", exampleMeaning: "carp / love" },
  // S row
  { char: "さ", romaji: "sa", row: "s", exampleWord: "さかな", exampleMeaning: "fish" },
  { char: "し", romaji: "shi", row: "s", exampleWord: "しか", exampleMeaning: "deer" },
  { char: "す", romaji: "su", row: "s", exampleWord: "すいか", exampleMeaning: "watermelon" },
  { char: "せ", romaji: "se", row: "s", exampleWord: "せみ", exampleMeaning: "cicada" },
  { char: "そ", romaji: "so", row: "s", exampleWord: "そら", exampleMeaning: "sky" },
  // T row
  { char: "た", romaji: "ta", row: "t", exampleWord: "たこ", exampleMeaning: "octopus / kite" },
  { char: "ち", romaji: "chi", row: "t", exampleWord: "ちょうちょ", exampleMeaning: "butterfly" },
  { char: "つ", romaji: "tsu", row: "t", exampleWord: "つき", exampleMeaning: "moon" },
  { char: "て", romaji: "te", row: "t", exampleWord: "てんとう", exampleMeaning: "ladybug" },
  { char: "と", romaji: "to", row: "t", exampleWord: "とり", exampleMeaning: "bird" },
  // N row
  { char: "な", romaji: "na", row: "n", exampleWord: "なす", exampleMeaning: "eggplant" },
  { char: "に", romaji: "ni", row: "n", exampleWord: "にじ", exampleMeaning: "rainbow" },
  { char: "ぬ", romaji: "nu", row: "n", exampleWord: "ぬいぐるみ", exampleMeaning: "stuffed toy" },
  { char: "ね", romaji: "ne", row: "n", exampleWord: "ねこ", exampleMeaning: "cat" },
  { char: "の", romaji: "no", row: "n", exampleWord: "のり", exampleMeaning: "seaweed / glue" },
  // H row
  { char: "は", romaji: "ha", row: "h", exampleWord: "はな", exampleMeaning: "flower / nose" },
  { char: "ひ", romaji: "hi", row: "h", exampleWord: "ひこうき", exampleMeaning: "airplane" },
  { char: "ふ", romaji: "fu", row: "h", exampleWord: "ふね", exampleMeaning: "ship" },
  { char: "へ", romaji: "he", row: "h", exampleWord: "へび", exampleMeaning: "snake" },
  { char: "ほ", romaji: "ho", row: "h", exampleWord: "ほし", exampleMeaning: "star" },
  // M row
  { char: "ま", romaji: "ma", row: "m", exampleWord: "まめ", exampleMeaning: "bean" },
  { char: "み", romaji: "mi", row: "m", exampleWord: "みかん", exampleMeaning: "mandarin orange" },
  { char: "む", romaji: "mu", row: "m", exampleWord: "むし", exampleMeaning: "insect" },
  { char: "め", romaji: "me", row: "m", exampleWord: "めだか", exampleMeaning: "killifish" },
  { char: "も", romaji: "mo", row: "m", exampleWord: "もも", exampleMeaning: "peach" },
  // Y row
  { char: "や", romaji: "ya", row: "y", exampleWord: "やま", exampleMeaning: "mountain" },
  { char: "ゆ", romaji: "yu", row: "y", exampleWord: "ゆき", exampleMeaning: "snow" },
  { char: "よ", romaji: "yo", row: "y", exampleWord: "よる", exampleMeaning: "night" },
  // R row
  { char: "ら", romaji: "ra", row: "r", exampleWord: "らくだ", exampleMeaning: "camel" },
  { char: "り", romaji: "ri", row: "r", exampleWord: "りす", exampleMeaning: "squirrel" },
  { char: "る", romaji: "ru", row: "r", exampleWord: "るび", exampleMeaning: "ruby" },
  { char: "れ", romaji: "re", row: "r", exampleWord: "れんこん", exampleMeaning: "lotus root" },
  { char: "ろ", romaji: "ro", row: "r", exampleWord: "ろうそく", exampleMeaning: "candle" },
  // W row
  { char: "わ", romaji: "wa", row: "w", exampleWord: "わに", exampleMeaning: "alligator" },
  { char: "を", romaji: "wo", row: "w", exampleWord: "を (particle)", exampleMeaning: "object marker" },
  // N
  { char: "ん", romaji: "n", row: "n2", exampleWord: "りんご", exampleMeaning: "apple" },

  // ── Dakuten (voiced) rows ─────────────────────────────────────────────────
  // G row
  { char: "が", romaji: "ga", row: "g", exampleWord: "がっこう", exampleMeaning: "school" },
  { char: "ぎ", romaji: "gi", row: "g", exampleWord: "ぎんこう", exampleMeaning: "bank" },
  { char: "ぐ", romaji: "gu", row: "g", exampleWord: "ぐつ", exampleMeaning: "shoes" },
  { char: "げ", romaji: "ge", row: "g", exampleWord: "げんき", exampleMeaning: "healthy / energetic" },
  { char: "ご", romaji: "go", row: "g", exampleWord: "ごはん", exampleMeaning: "rice / meal" },
  // Z row
  { char: "ざ", romaji: "za", row: "z", exampleWord: "ざっし", exampleMeaning: "magazine" },
  { char: "じ", romaji: "ji", row: "z", exampleWord: "じかん", exampleMeaning: "time" },
  { char: "ず", romaji: "zu", row: "z", exampleWord: "ずかん", exampleMeaning: "illustrated book" },
  { char: "ぜ", romaji: "ze", row: "z", exampleWord: "ぜんぶ", exampleMeaning: "all / everything" },
  { char: "ぞ", romaji: "zo", row: "z", exampleWord: "ぞう", exampleMeaning: "elephant" },
  // D row
  { char: "だ", romaji: "da", row: "d", exampleWord: "だいすき", exampleMeaning: "love (it)" },
  { char: "ぢ", romaji: "di", row: "d", exampleWord: "ちぢむ", exampleMeaning: "to shrink" },
  { char: "づ", romaji: "du", row: "d", exampleWord: "つづく", exampleMeaning: "to continue" },
  { char: "で", romaji: "de", row: "d", exampleWord: "でんしゃ", exampleMeaning: "train" },
  { char: "ど", romaji: "do", row: "d", exampleWord: "どうぶつ", exampleMeaning: "animal" },
  // B row
  { char: "ば", romaji: "ba", row: "b", exampleWord: "ばなな", exampleMeaning: "banana" },
  { char: "び", romaji: "bi", row: "b", exampleWord: "びじゅつ", exampleMeaning: "art" },
  { char: "ぶ", romaji: "bu", row: "b", exampleWord: "ぶどう", exampleMeaning: "grapes" },
  { char: "べ", romaji: "be", row: "b", exampleWord: "べんきょう", exampleMeaning: "study" },
  { char: "ぼ", romaji: "bo", row: "b", exampleWord: "ぼうし", exampleMeaning: "hat" },
  // P row (handakuten)
  { char: "ぱ", romaji: "pa", row: "p", exampleWord: "ぱんだ", exampleMeaning: "panda" },
  { char: "ぴ", romaji: "pi", row: "p", exampleWord: "ぴかぴか", exampleMeaning: "shiny / sparkly" },
  { char: "ぷ", romaji: "pu", row: "p", exampleWord: "ぷりん", exampleMeaning: "pudding" },
  { char: "ぺ", romaji: "pe", row: "p", exampleWord: "ぺんぎん", exampleMeaning: "penguin" },
  { char: "ぽ", romaji: "po", row: "p", exampleWord: "ぽすと", exampleMeaning: "mailbox" },

  // ── Combination characters (consonant + や/ゆ/よ) ─────────────────────────
  { char: "きゃ", romaji: "kya", row: "combo", exampleWord: "きゃく", exampleMeaning: "guest" },
  { char: "きゅ", romaji: "kyu", row: "combo", exampleWord: "きゅうり", exampleMeaning: "cucumber" },
  { char: "きょ", romaji: "kyo", row: "combo", exampleWord: "きょうしつ", exampleMeaning: "classroom" },
  { char: "ぎゃ", romaji: "gya", row: "combo", exampleWord: "ぎゃく", exampleMeaning: "reverse" },
  { char: "ぎゅ", romaji: "gyu", row: "combo", exampleWord: "ぎゅうにゅう", exampleMeaning: "milk" },
  { char: "ぎょ", romaji: "gyo", row: "combo", exampleWord: "ぎょうざ", exampleMeaning: "gyoza dumpling" },
  { char: "しゃ", romaji: "sha", row: "combo", exampleWord: "しゃしん", exampleMeaning: "photo" },
  { char: "しゅ", romaji: "shu", row: "combo", exampleWord: "しゅくだい", exampleMeaning: "homework" },
  { char: "しょ", romaji: "sho", row: "combo", exampleWord: "しょうがっこう", exampleMeaning: "elementary school" },
  { char: "じゃ", romaji: "ja", row: "combo", exampleWord: "じゃあ", exampleMeaning: "well then" },
  { char: "じゅ", romaji: "ju", row: "combo", exampleWord: "じゅぎょう", exampleMeaning: "class / lesson" },
  { char: "じょ", romaji: "jo", row: "combo", exampleWord: "じょうず", exampleMeaning: "skilled / good at" },
  { char: "ちゃ", romaji: "cha", row: "combo", exampleWord: "おちゃ", exampleMeaning: "tea" },
  { char: "ちゅ", romaji: "chu", row: "combo", exampleWord: "ちゅうごく", exampleMeaning: "China" },
  { char: "ちょ", romaji: "cho", row: "combo", exampleWord: "ちょうちょ", exampleMeaning: "butterfly" },
  { char: "にゃ", romaji: "nya", row: "combo", exampleWord: "にゃんこ", exampleMeaning: "kitty" },
  { char: "にゅ", romaji: "nyu", row: "combo", exampleWord: "にゅうがく", exampleMeaning: "school enrollment" },
  { char: "にょ", romaji: "nyo", row: "combo", exampleWord: "にょろにょろ", exampleMeaning: "wriggly" },
  { char: "ひゃ", romaji: "hya", row: "combo", exampleWord: "ひゃく", exampleMeaning: "one hundred" },
  { char: "ひゅ", romaji: "hyu", row: "combo", exampleWord: "ひゅーひゅー", exampleMeaning: "whooshing sound" },
  { char: "ひょ", romaji: "hyo", row: "combo", exampleWord: "ひょう", exampleMeaning: "hail / leopard" },
  { char: "びゃ", romaji: "bya", row: "combo", exampleWord: "びゃく", exampleMeaning: "white (classical)" },
  { char: "びゅ", romaji: "byu", row: "combo", exampleWord: "びゅーびゅー", exampleMeaning: "whooshing wind" },
  { char: "びょ", romaji: "byo", row: "combo", exampleWord: "びょうき", exampleMeaning: "illness" },
  { char: "みゃ", romaji: "mya", row: "combo", exampleWord: "みゃく", exampleMeaning: "pulse" },
  { char: "みゅ", romaji: "myu", row: "combo", exampleWord: "みゅーじっく", exampleMeaning: "music" },
  { char: "みょ", romaji: "myo", row: "combo", exampleWord: "みょうじ", exampleMeaning: "surname" },
  { char: "ぴゃ", romaji: "pya", row: "combo", exampleWord: "ぴゃーぴゃー", exampleMeaning: "squeaking sound" },
  { char: "ぴゅ", romaji: "pyu", row: "combo", exampleWord: "ぴゅーぴゅー", exampleMeaning: "whistling wind" },
  { char: "ぴょ", romaji: "pyo", row: "combo", exampleWord: "ぴょんぴょん", exampleMeaning: "hopping" },
  { char: "りゃ", romaji: "rya", row: "combo", exampleWord: "りゃくご", exampleMeaning: "abbreviation" },
  { char: "りゅ", romaji: "ryu", row: "combo", exampleWord: "りゅう", exampleMeaning: "dragon" },
  { char: "りょ", romaji: "ryo", row: "combo", exampleWord: "りょこう", exampleMeaning: "travel" },
];
