import { KanaChar } from "@/types";

export const KATAKANA: KanaChar[] = [
  // A row
  { char: "ア", romaji: "a", row: "a", exampleWord: "アイスクリーム", exampleMeaning: "ice cream" },
  { char: "イ", romaji: "i", row: "a", exampleWord: "イルカ", exampleMeaning: "dolphin" },
  { char: "ウ", romaji: "u", row: "a", exampleWord: "ウサギ", exampleMeaning: "rabbit" },
  { char: "エ", romaji: "e", row: "a", exampleWord: "エビ", exampleMeaning: "shrimp" },
  { char: "オ", romaji: "o", row: "a", exampleWord: "オレンジ", exampleMeaning: "orange" },
  // K row
  { char: "カ", romaji: "ka", row: "k", exampleWord: "カメ", exampleMeaning: "turtle" },
  { char: "キ", romaji: "ki", row: "k", exampleWord: "キリン", exampleMeaning: "giraffe" },
  { char: "ク", romaji: "ku", row: "k", exampleWord: "クマ", exampleMeaning: "bear" },
  { char: "ケ", romaji: "ke", row: "k", exampleWord: "ケーキ", exampleMeaning: "cake" },
  { char: "コ", romaji: "ko", row: "k", exampleWord: "コーヒー", exampleMeaning: "coffee" },
  // S row
  { char: "サ", romaji: "sa", row: "s", exampleWord: "サクラ", exampleMeaning: "cherry blossom" },
  { char: "シ", romaji: "shi", row: "s", exampleWord: "シマウマ", exampleMeaning: "zebra" },
  { char: "ス", romaji: "su", row: "s", exampleWord: "スイカ", exampleMeaning: "watermelon" },
  { char: "セ", romaji: "se", row: "s", exampleWord: "セーター", exampleMeaning: "sweater" },
  { char: "ソ", romaji: "so", row: "s", exampleWord: "ソファ", exampleMeaning: "sofa" },
  // T row
  { char: "タ", romaji: "ta", row: "t", exampleWord: "タコ", exampleMeaning: "octopus" },
  { char: "チ", romaji: "chi", row: "t", exampleWord: "チーズ", exampleMeaning: "cheese" },
  { char: "ツ", romaji: "tsu", row: "t", exampleWord: "ツリー", exampleMeaning: "tree" },
  { char: "テ", romaji: "te", row: "t", exampleWord: "テレビ", exampleMeaning: "television" },
  { char: "ト", romaji: "to", row: "t", exampleWord: "トラ", exampleMeaning: "tiger" },
  // N row
  { char: "ナ", romaji: "na", row: "n", exampleWord: "ナイフ", exampleMeaning: "knife" },
  { char: "ニ", romaji: "ni", row: "n", exampleWord: "ニンジン", exampleMeaning: "carrot" },
  { char: "ヌ", romaji: "nu", row: "n", exampleWord: "ヌードル", exampleMeaning: "noodle" },
  { char: "ネ", romaji: "ne", row: "n", exampleWord: "ネコ", exampleMeaning: "cat" },
  { char: "ノ", romaji: "no", row: "n", exampleWord: "ノート", exampleMeaning: "notebook" },
  // H row
  { char: "ハ", romaji: "ha", row: "h", exampleWord: "ハンバーガー", exampleMeaning: "hamburger" },
  { char: "ヒ", romaji: "hi", row: "h", exampleWord: "ヒツジ", exampleMeaning: "sheep" },
  { char: "フ", romaji: "fu", row: "h", exampleWord: "フルーツ", exampleMeaning: "fruit" },
  { char: "ヘ", romaji: "he", row: "h", exampleWord: "ヘリコプター", exampleMeaning: "helicopter" },
  { char: "ホ", romaji: "ho", row: "h", exampleWord: "ホテル", exampleMeaning: "hotel" },
  // M row
  { char: "マ", romaji: "ma", row: "m", exampleWord: "マンゴー", exampleMeaning: "mango" },
  { char: "ミ", romaji: "mi", row: "m", exampleWord: "ミルク", exampleMeaning: "milk" },
  { char: "ム", romaji: "mu", row: "m", exampleWord: "ムービー", exampleMeaning: "movie" },
  { char: "メ", romaji: "me", row: "m", exampleWord: "メロン", exampleMeaning: "melon" },
  { char: "モ", romaji: "mo", row: "m", exampleWord: "モンスター", exampleMeaning: "monster" },
  // Y row
  { char: "ヤ", romaji: "ya", row: "y", exampleWord: "ヤシ", exampleMeaning: "palm tree" },
  { char: "ユ", romaji: "yu", row: "y", exampleWord: "ユニコーン", exampleMeaning: "unicorn" },
  { char: "ヨ", romaji: "yo", row: "y", exampleWord: "ヨーグルト", exampleMeaning: "yogurt" },
  // R row
  { char: "ラ", romaji: "ra", row: "r", exampleWord: "ライオン", exampleMeaning: "lion" },
  { char: "リ", romaji: "ri", row: "r", exampleWord: "リンゴ", exampleMeaning: "apple" },
  { char: "ル", romaji: "ru", row: "r", exampleWord: "ルビー", exampleMeaning: "ruby" },
  { char: "レ", romaji: "re", row: "r", exampleWord: "レモン", exampleMeaning: "lemon" },
  { char: "ロ", romaji: "ro", row: "r", exampleWord: "ロボット", exampleMeaning: "robot" },
  // W row
  { char: "ワ", romaji: "wa", row: "w", exampleWord: "ワニ", exampleMeaning: "alligator" },
  { char: "ヲ", romaji: "wo", row: "w", exampleWord: "ヲ (particle)", exampleMeaning: "object marker" },
  // N
  { char: "ン", romaji: "n", row: "n2", exampleWord: "パン", exampleMeaning: "bread" },

  // ── Dakuten (voiced) rows ─────────────────────────────────────────────────
  // G row
  { char: "ガ", romaji: "ga", row: "g", exampleWord: "ガム", exampleMeaning: "gum" },
  { char: "ギ", romaji: "gi", row: "g", exampleWord: "ギター", exampleMeaning: "guitar" },
  { char: "グ", romaji: "gu", row: "g", exampleWord: "グループ", exampleMeaning: "group" },
  { char: "ゲ", romaji: "ge", row: "g", exampleWord: "ゲーム", exampleMeaning: "game" },
  { char: "ゴ", romaji: "go", row: "g", exampleWord: "ゴリラ", exampleMeaning: "gorilla" },
  // Z row
  { char: "ザ", romaji: "za", row: "z", exampleWord: "ザリガニ", exampleMeaning: "crayfish" },
  { char: "ジ", romaji: "ji", row: "z", exampleWord: "ジュース", exampleMeaning: "juice" },
  { char: "ズ", romaji: "zu", row: "z", exampleWord: "ズボン", exampleMeaning: "trousers" },
  { char: "ゼ", romaji: "ze", row: "z", exampleWord: "ゼリー", exampleMeaning: "jelly" },
  { char: "ゾ", romaji: "zo", row: "z", exampleWord: "ゾンビ", exampleMeaning: "zombie" },
  // D row
  { char: "ダ", romaji: "da", row: "d", exampleWord: "ダンス", exampleMeaning: "dance" },
  { char: "ヂ", romaji: "di", row: "d", exampleWord: "ヂュース", exampleMeaning: "juice (alt)" },
  { char: "ヅ", romaji: "du", row: "d", exampleWord: "ヅメ", exampleMeaning: "claw (alt)" },
  { char: "デ", romaji: "de", row: "d", exampleWord: "デザート", exampleMeaning: "dessert" },
  { char: "ド", romaji: "do", row: "d", exampleWord: "ドラゴン", exampleMeaning: "dragon" },
  // B row
  { char: "バ", romaji: "ba", row: "b", exampleWord: "バナナ", exampleMeaning: "banana" },
  { char: "ビ", romaji: "bi", row: "b", exampleWord: "ビール", exampleMeaning: "beer" },
  { char: "ブ", romaji: "bu", row: "b", exampleWord: "ブドウ", exampleMeaning: "grapes" },
  { char: "ベ", romaji: "be", row: "b", exampleWord: "ベッド", exampleMeaning: "bed" },
  { char: "ボ", romaji: "bo", row: "b", exampleWord: "ボール", exampleMeaning: "ball" },
  // P row (handakuten)
  { char: "パ", romaji: "pa", row: "p", exampleWord: "パンダ", exampleMeaning: "panda" },
  { char: "ピ", romaji: "pi", row: "p", exampleWord: "ピアノ", exampleMeaning: "piano" },
  { char: "プ", romaji: "pu", row: "p", exampleWord: "プリン", exampleMeaning: "pudding" },
  { char: "ペ", romaji: "pe", row: "p", exampleWord: "ペンギン", exampleMeaning: "penguin" },
  { char: "ポ", romaji: "po", row: "p", exampleWord: "ポップコーン", exampleMeaning: "popcorn" },

  // ── Combination characters (consonant + ャ/ュ/ョ) ─────────────────────────
  { char: "キャ", romaji: "kya", row: "combo", exampleWord: "キャンプ", exampleMeaning: "camping" },
  { char: "キュ", romaji: "kyu", row: "combo", exampleWord: "キュウリ", exampleMeaning: "cucumber" },
  { char: "キョ", romaji: "kyo", row: "combo", exampleWord: "キョウリュウ", exampleMeaning: "dinosaur" },
  { char: "ギャ", romaji: "gya", row: "combo", exampleWord: "ギャグ", exampleMeaning: "joke / gag" },
  { char: "ギュ", romaji: "gyu", row: "combo", exampleWord: "ギュウニュウ", exampleMeaning: "milk" },
  { char: "ギョ", romaji: "gyo", row: "combo", exampleWord: "ギョウザ", exampleMeaning: "gyoza dumpling" },
  { char: "シャ", romaji: "sha", row: "combo", exampleWord: "シャワー", exampleMeaning: "shower" },
  { char: "シュ", romaji: "shu", row: "combo", exampleWord: "シュークリーム", exampleMeaning: "cream puff" },
  { char: "ショ", romaji: "sho", row: "combo", exampleWord: "ショコラ", exampleMeaning: "chocolate" },
  { char: "ジャ", romaji: "ja", row: "combo", exampleWord: "ジャングル", exampleMeaning: "jungle" },
  { char: "ジュ", romaji: "ju", row: "combo", exampleWord: "ジュース", exampleMeaning: "juice" },
  { char: "ジョ", romaji: "jo", row: "combo", exampleWord: "ジョギング", exampleMeaning: "jogging" },
  { char: "チャ", romaji: "cha", row: "combo", exampleWord: "チャンス", exampleMeaning: "chance" },
  { char: "チュ", romaji: "chu", row: "combo", exampleWord: "チューリップ", exampleMeaning: "tulip" },
  { char: "チョ", romaji: "cho", row: "combo", exampleWord: "チョコレート", exampleMeaning: "chocolate" },
  { char: "ニャ", romaji: "nya", row: "combo", exampleWord: "ニャンコ", exampleMeaning: "kitty" },
  { char: "ニュ", romaji: "nyu", row: "combo", exampleWord: "ニュース", exampleMeaning: "news" },
  { char: "ニョ", romaji: "nyo", row: "combo", exampleWord: "ニョッキ", exampleMeaning: "gnocchi" },
  { char: "ヒャ", romaji: "hya", row: "combo", exampleWord: "ヒャク", exampleMeaning: "one hundred" },
  { char: "ヒュ", romaji: "hyu", row: "combo", exampleWord: "ヒューズ", exampleMeaning: "fuse" },
  { char: "ヒョ", romaji: "hyo", row: "combo", exampleWord: "ヒョウ", exampleMeaning: "leopard" },
  { char: "ビャ", romaji: "bya", row: "combo", exampleWord: "ビャクヤ", exampleMeaning: "white night" },
  { char: "ビュ", romaji: "byu", row: "combo", exampleWord: "ビュッフェ", exampleMeaning: "buffet" },
  { char: "ビョ", romaji: "byo", row: "combo", exampleWord: "ビョウキ", exampleMeaning: "illness" },
  { char: "ミャ", romaji: "mya", row: "combo", exampleWord: "ミャンマー", exampleMeaning: "Myanmar" },
  { char: "ミュ", romaji: "myu", row: "combo", exampleWord: "ミュージック", exampleMeaning: "music" },
  { char: "ミョ", romaji: "myo", row: "combo", exampleWord: "ミョウジ", exampleMeaning: "surname" },
  { char: "ピャ", romaji: "pya", row: "combo", exampleWord: "ピャーピャー", exampleMeaning: "squeaking sound" },
  { char: "ピュ", romaji: "pyu", row: "combo", exampleWord: "ピューマ", exampleMeaning: "puma" },
  { char: "ピョ", romaji: "pyo", row: "combo", exampleWord: "ピョンピョン", exampleMeaning: "hopping" },
  { char: "リャ", romaji: "rya", row: "combo", exampleWord: "リャクゴ", exampleMeaning: "abbreviation" },
  { char: "リュ", romaji: "ryu", row: "combo", exampleWord: "リュック", exampleMeaning: "backpack" },
  { char: "リョ", romaji: "ryo", row: "combo", exampleWord: "リョコウ", exampleMeaning: "travel" },
];
