export interface ThemeWord {
  emoji: string;
  japanese: string;
  romaji: string;
  english: string;
}

export interface Theme {
  id: string;
  label: string;
  icon: string;
  activeColor: string;   // hex — active tab + card highlight
  borderHex: string;     // hex — card border
  bg: string;            // Tailwind gradient classes
  layout?: "scatter" | "calendar" | "ordered-grid";
  columns?: number;      // for ordered-grid layout
  words: ThemeWord[];
  isSentences?: boolean;
}

export const THEMES: Theme[] = [
  // ── Numbers ──────────────────────────────────────────────────────────────
  {
    id: "numbers-1-10",
    label: "1〜10",
    icon: "🔢",
    activeColor: "#0ea5e9",
    borderHex: "#7dd3fc",
    bg: "from-sky-50 via-blue-50 to-cyan-50",
    layout: "ordered-grid",
    columns: 5,
    words: [
      { emoji: "1",  japanese: "いち",   romaji: "ichi",   english: "1" },
      { emoji: "2",  japanese: "に",     romaji: "ni",     english: "2" },
      { emoji: "3",  japanese: "さん",   romaji: "san",    english: "3" },
      { emoji: "4",  japanese: "よん",   romaji: "yon",    english: "4" },
      { emoji: "5",  japanese: "ご",     romaji: "go",     english: "5" },
      { emoji: "6",  japanese: "ろく",   romaji: "roku",   english: "6" },
      { emoji: "7",  japanese: "なな",   romaji: "nana",   english: "7" },
      { emoji: "8",  japanese: "はち",   romaji: "hachi",  english: "8" },
      { emoji: "9",  japanese: "きゅう", romaji: "kyuu",   english: "9" },
      { emoji: "10", japanese: "じゅう", romaji: "juu",    english: "10" },
    ],
  },
  {
    id: "numbers-tens",
    label: "10〜100",
    icon: "💯",
    activeColor: "#6366f1",
    borderHex: "#a5b4fc",
    bg: "from-indigo-50 via-blue-50 to-violet-50",
    layout: "ordered-grid",
    columns: 5,
    words: [
      { emoji: "10",  japanese: "じゅう",       romaji: "juu",       english: "10" },
      { emoji: "20",  japanese: "にじゅう",     romaji: "nijuu",     english: "20" },
      { emoji: "30",  japanese: "さんじゅう",   romaji: "sanjuu",    english: "30" },
      { emoji: "40",  japanese: "よんじゅう",   romaji: "yonjuu",    english: "40" },
      { emoji: "50",  japanese: "ごじゅう",     romaji: "gojuu",     english: "50" },
      { emoji: "60",  japanese: "ろくじゅう",   romaji: "rokujuu",   english: "60" },
      { emoji: "70",  japanese: "ななじゅう",   romaji: "nanajuu",   english: "70" },
      { emoji: "80",  japanese: "はちじゅう",   romaji: "hachijuu",  english: "80" },
      { emoji: "90",  japanese: "きゅうじゅう", romaji: "kyuujuu",   english: "90" },
      { emoji: "100", japanese: "ひゃく",       romaji: "hyaku",     english: "100" },
    ],
  },
  {
    id: "numbers-hundreds",
    label: "100〜1000",
    icon: "🏦",
    activeColor: "#14b8a6",
    borderHex: "#5eead4",
    bg: "from-teal-50 via-emerald-50 to-cyan-50",
    layout: "ordered-grid",
    columns: 5,
    words: [
      { emoji: "100",  japanese: "ひゃく",       romaji: "hyaku",      english: "100" },
      { emoji: "200",  japanese: "にひゃく",     romaji: "nihyaku",    english: "200" },
      { emoji: "300",  japanese: "さんびゃく",   romaji: "sanbyaku",   english: "300" },
      { emoji: "400",  japanese: "よんひゃく",   romaji: "yonhyaku",   english: "400" },
      { emoji: "500",  japanese: "ごひゃく",     romaji: "gohyaku",    english: "500" },
      { emoji: "600",  japanese: "ろっぴゃく",   romaji: "roppyaku",   english: "600" },
      { emoji: "700",  japanese: "ななひゃく",   romaji: "nanahyaku",  english: "700" },
      { emoji: "800",  japanese: "はっぴゃく",   romaji: "happyaku",   english: "800" },
      { emoji: "900",  japanese: "きゅうひゃく", romaji: "kyuuhyaku",  english: "900" },
      { emoji: "1000", japanese: "せん",         romaji: "sen",        english: "1000" },
    ],
  },
  // ── Calendar ─────────────────────────────────────────────────────────────
  {
    id: "weekdays",
    label: "Weekdays",
    icon: "📅",
    activeColor: "#8b5cf6",
    borderHex: "#c4b5fd",
    bg: "from-violet-50 via-purple-50 to-indigo-50",
    layout: "calendar",
    words: [
      { emoji: "月", japanese: "げつようび", romaji: "getsuyoubi", english: "Monday" },
      { emoji: "火", japanese: "かようび",   romaji: "kayoubi",    english: "Tuesday" },
      { emoji: "水", japanese: "すいようび", romaji: "suiyoubi",   english: "Wednesday" },
      { emoji: "木", japanese: "もくようび", romaji: "mokuyoubi",  english: "Thursday" },
      { emoji: "金", japanese: "きんようび", romaji: "kinyoubi",   english: "Friday" },
      { emoji: "土", japanese: "どようび",   romaji: "doyoubi",    english: "Saturday" },
      { emoji: "日", japanese: "にちようび", romaji: "nichiyoubi", english: "Sunday" },
      { emoji: "📅", japanese: "きょう",     romaji: "kyou",       english: "Today" },
      { emoji: "➡️", japanese: "あした",     romaji: "ashita",     english: "Tomorrow" },
      { emoji: "⬅️", japanese: "きのう",     romaji: "kinou",      english: "Yesterday" },
      { emoji: "先週", japanese: "せんしゅう", romaji: "senshuu",  english: "Last week" },
      { emoji: "今週", japanese: "こんしゅう", romaji: "konshuu",  english: "This week" },
      { emoji: "来週", japanese: "らいしゅう", romaji: "raishuu",  english: "Next week" },
      { emoji: "🏖️", japanese: "しゅうまつ", romaji: "shuumatsu",  english: "Weekend" },
    ],
  },
  {
    id: "days-of-month",
    label: "月の日",
    icon: "🗓️",
    activeColor: "#f43f5e",
    borderHex: "#fda4af",
    bg: "from-rose-50 via-pink-50 to-orange-50",
    layout: "ordered-grid",
    columns: 7,
    words: [
      { emoji: "1",  japanese: "ついたち",           romaji: "tsuitachi",        english: "1st" },
      { emoji: "2",  japanese: "ふつか",             romaji: "futsuka",          english: "2nd" },
      { emoji: "3",  japanese: "みっか",             romaji: "mikka",            english: "3rd" },
      { emoji: "4",  japanese: "よっか",             romaji: "yokka",            english: "4th" },
      { emoji: "5",  japanese: "いつか",             romaji: "itsuka",           english: "5th" },
      { emoji: "6",  japanese: "むいか",             romaji: "muika",            english: "6th" },
      { emoji: "7",  japanese: "なのか",             romaji: "nanoka",           english: "7th" },
      { emoji: "8",  japanese: "ようか",             romaji: "youka",            english: "8th" },
      { emoji: "9",  japanese: "ここのか",           romaji: "kokonoka",         english: "9th" },
      { emoji: "10", japanese: "とおか",             romaji: "tooka",            english: "10th" },
      { emoji: "11", japanese: "じゅういちにち",     romaji: "juuichinichi",     english: "11th" },
      { emoji: "12", japanese: "じゅうににち",       romaji: "juuninichi",       english: "12th" },
      { emoji: "13", japanese: "じゅうさんにち",     romaji: "juusannichi",      english: "13th" },
      { emoji: "14", japanese: "じゅうよっか",       romaji: "juuyokka",         english: "14th" },
      { emoji: "15", japanese: "じゅうごにち",       romaji: "juugonichi",       english: "15th" },
      { emoji: "16", japanese: "じゅうろくにち",     romaji: "juurokunichi",     english: "16th" },
      { emoji: "17", japanese: "じゅうしちにち",     romaji: "juushichinichi",   english: "17th" },
      { emoji: "18", japanese: "じゅうはちにち",     romaji: "juuhachinichi",    english: "18th" },
      { emoji: "19", japanese: "じゅうくにち",       romaji: "juukunichi",       english: "19th" },
      { emoji: "20", japanese: "はつか",             romaji: "hatsuka",          english: "20th" },
      { emoji: "21", japanese: "にじゅういちにち",   romaji: "nijuuichinichi",   english: "21st" },
      { emoji: "22", japanese: "にじゅうににち",     romaji: "nijuuninichi",     english: "22nd" },
      { emoji: "23", japanese: "にじゅうさんにち",   romaji: "nijuusannichi",    english: "23rd" },
      { emoji: "24", japanese: "にじゅうよっか",     romaji: "nijuuyokka",       english: "24th" },
      { emoji: "25", japanese: "にじゅうごにち",     romaji: "nijuugonichi",     english: "25th" },
      { emoji: "26", japanese: "にじゅうろくにち",   romaji: "nijuurokunichi",   english: "26th" },
      { emoji: "27", japanese: "にじゅうしちにち",   romaji: "nijuushichinichi", english: "27th" },
      { emoji: "28", japanese: "にじゅうはちにち",   romaji: "nijuuhachinichi",  english: "28th" },
      { emoji: "29", japanese: "にじゅうくにち",     romaji: "nijuukunichi",     english: "29th" },
      { emoji: "30", japanese: "さんじゅうにち",     romaji: "sanjuunichi",      english: "30th" },
      { emoji: "31", japanese: "さんじゅういちにち", romaji: "sanjuuichinichi",  english: "31st" },
    ],
  },
  // ── Scatter themes ────────────────────────────────────────────────────────
  {
    id: "swimming",
    label: "Swimming",
    icon: "🏊",
    activeColor: "#3b82f6",
    borderHex: "#93c5fd",
    bg: "from-blue-50 via-cyan-50 to-sky-50",
    words: [
      { emoji: "🏊", japanese: "およぐ",       romaji: "oyogu",         english: "Swim" },
      { emoji: "🏖️", japanese: "プール",       romaji: "puuru",         english: "Pool" },
      { emoji: "🩱", japanese: "みずぎ",       romaji: "mizugi",        english: "Swimsuit" },
      { emoji: "🥽", japanese: "ゴーグル",     romaji: "googuru",       english: "Goggles" },
      { emoji: "💧", japanese: "みず",         romaji: "mizu",          english: "Water" },
      { emoji: "🌊", japanese: "なみ",         romaji: "nami",          english: "Wave" },
      { emoji: "🤿", japanese: "もぐる",       romaji: "moguru",        english: "Dive" },
      { emoji: "🏄", japanese: "サーフィン",   romaji: "saafin",        english: "Surfing" },
      { emoji: "🎽", japanese: "キャップ",     romaji: "kyappu",        english: "Swim Cap" },
      { emoji: "🏆", japanese: "きょうそう",   romaji: "kyousou",       english: "Race" },
      { emoji: "🦈", japanese: "さめ",         romaji: "same",          english: "Shark" },
      { emoji: "🐟", japanese: "さかな",       romaji: "sakana",        english: "Fish" },
      { emoji: "🫁", japanese: "いきをとめる", romaji: "iki wo tomeru", english: "Hold Breath" },
      { emoji: "🪸", japanese: "うみ",         romaji: "umi",           english: "Ocean" },
    ],
  },
  {
    id: "school-commute",
    label: "To School",
    icon: "🎒",
    activeColor: "#f97316",
    borderHex: "#fdba74",
    bg: "from-orange-50 via-yellow-50 to-amber-50",
    words: [
      { emoji: "🎒", japanese: "ランドセル",   romaji: "randoseru",    english: "School Bag" },
      { emoji: "🚌", japanese: "スクールバス", romaji: "sukuuru basu", english: "School Bus" },
      { emoji: "🚶", japanese: "あるく",       romaji: "aruku",        english: "Walk" },
      { emoji: "🚲", japanese: "じてんしゃ",   romaji: "jitensha",     english: "Bicycle" },
      { emoji: "⏰", japanese: "じかん",       romaji: "jikan",        english: "Time" },
      { emoji: "🏫", japanese: "がっこう",     romaji: "gakkou",       english: "School" },
      { emoji: "🍱", japanese: "おべんとう",   romaji: "obentou",      english: "Lunch Box" },
      { emoji: "👟", japanese: "くつ",         romaji: "kutsu",        english: "Shoes" },
      { emoji: "🧢", japanese: "ぼうし",       romaji: "boushi",       english: "Hat" },
      { emoji: "🌅", japanese: "あさ",         romaji: "asa",          english: "Morning" },
      { emoji: "👋", japanese: "いってきます", romaji: "ittekimasu",   english: "I'm leaving!" },
      { emoji: "🏃", japanese: "はしる",       romaji: "hashiru",      english: "Run" },
      { emoji: "🗺️", japanese: "みち",         romaji: "michi",        english: "Road" },
      { emoji: "🚦", japanese: "しんごう",     romaji: "shingou",      english: "Traffic Light" },
    ],
  },
  {
    id: "shopping",
    label: "Shopping",
    icon: "🛒",
    activeColor: "#ec4899",
    borderHex: "#f9a8d4",
    bg: "from-pink-50 via-rose-50 to-fuchsia-50",
    words: [
      { emoji: "🛒", japanese: "カート",           romaji: "kaato",          english: "Cart" },
      { emoji: "💰", japanese: "おかね",           romaji: "okane",          english: "Money" },
      { emoji: "🏪", japanese: "おみせ",           romaji: "omise",          english: "Shop" },
      { emoji: "👜", japanese: "かばん",           romaji: "kaban",          english: "Bag" },
      { emoji: "💳", japanese: "カード",           romaji: "kaado",          english: "Card" },
      { emoji: "🛍️", japanese: "かいものぶくろ",   romaji: "kaimono bukuro", english: "Shopping Bag" },
      { emoji: "🧾", japanese: "レシート",         romaji: "reshiito",       english: "Receipt" },
      { emoji: "👗", japanese: "ふく",             romaji: "fuku",           english: "Clothes" },
      { emoji: "🍎", japanese: "くだもの",         romaji: "kudamono",       english: "Fruit" },
      { emoji: "🥦", japanese: "やさい",           romaji: "yasai",          english: "Vegetable" },
      { emoji: "🏷️", japanese: "ねだん",           romaji: "nedan",          english: "Price" },
      { emoji: "🤑", japanese: "やすい",           romaji: "yasui",          english: "Cheap" },
      { emoji: "💎", japanese: "たかい",           romaji: "takai",          english: "Expensive" },
      { emoji: "🧴", japanese: "せんざい",         romaji: "senzai",         english: "Detergent" },
    ],
  },
  {
    id: "hospital",
    label: "Hospital",
    icon: "🏥",
    activeColor: "#ef4444",
    borderHex: "#fca5a5",
    bg: "from-red-50 via-rose-50 to-orange-50",
    words: [
      { emoji: "🏥", japanese: "びょういん",       romaji: "byouin",       english: "Hospital" },
      { emoji: "👨‍⚕️", japanese: "いしゃ",          romaji: "isha",         english: "Doctor" },
      { emoji: "👩‍⚕️", japanese: "かんごし",        romaji: "kangoshi",     english: "Nurse" },
      { emoji: "💊", japanese: "くすり",           romaji: "kusuri",       english: "Medicine" },
      { emoji: "🩹", japanese: "ばんそうこう",     romaji: "bansoukou",    english: "Bandage" },
      { emoji: "🌡️", japanese: "たいおんけい",     romaji: "taionkei",     english: "Thermometer" },
      { emoji: "💉", japanese: "ちゅうしゃ",       romaji: "chuusha",      english: "Injection" },
      { emoji: "🚑", japanese: "きゅうきゅうしゃ", romaji: "kyuukyuusha",  english: "Ambulance" },
      { emoji: "🩺", japanese: "しんさつ",         romaji: "shinsatsu",    english: "Checkup" },
      { emoji: "🦷", japanese: "はいしゃ",         romaji: "haisha",       english: "Dentist" },
      { emoji: "😷", japanese: "マスク",           romaji: "masuku",       english: "Mask" },
      { emoji: "🛏️", japanese: "にゅういん",       romaji: "nyuuin",       english: "Hospitalized" },
      { emoji: "😰", japanese: "いたい",           romaji: "itai",         english: "Hurt / Pain" },
      { emoji: "💪", japanese: "げんき",           romaji: "genki",        english: "Healthy" },
    ],
  },
  {
    id: "school",
    label: "School",
    icon: "🏫",
    activeColor: "#22c55e",
    borderHex: "#86efac",
    bg: "from-green-50 via-emerald-50 to-teal-50",
    words: [
      { emoji: "🏫", japanese: "がっこう",       romaji: "gakkou",     english: "School" },
      { emoji: "👨‍🏫", japanese: "せんせい",       romaji: "sensei",     english: "Teacher" },
      { emoji: "🧑‍🎓", japanese: "せいと",         romaji: "seito",      english: "Student" },
      { emoji: "✏️", japanese: "えんぴつ",       romaji: "enpitsu",    english: "Pencil" },
      { emoji: "📚", japanese: "きょうかしょ",   romaji: "kyoukasho",  english: "Textbook" },
      { emoji: "🪑", japanese: "つくえ",         romaji: "tsukue",     english: "Desk" },
      { emoji: "🖊️", japanese: "ペン",           romaji: "pen",        english: "Pen" },
      { emoji: "📐", japanese: "じょうぎ",       romaji: "jougi",      english: "Ruler" },
      { emoji: "✂️", japanese: "はさみ",         romaji: "hasami",     english: "Scissors" },
      { emoji: "🖥️", japanese: "コンピューター", romaji: "konpyuutaa", english: "Computer" },
      { emoji: "🖼️", japanese: "こくばん",       romaji: "kokuban",    english: "Blackboard" },
      { emoji: "🗑️", japanese: "ごみばこ",       romaji: "gomibako",   english: "Trash Can" },
      { emoji: "📝", japanese: "ノート",         romaji: "nooto",      english: "Notebook" },
      { emoji: "🔔", japanese: "チャイム",       romaji: "chaimu",     english: "Bell / Chime" },
    ],
  },
  // ── Sentence themes ───────────────────────────────────────────────────────
  {
    id: "shopping-sentences",
    label: "Shopping Talk",
    icon: "🗣️",
    activeColor: "#f59e0b",
    borderHex: "#fcd34d",
    bg: "from-amber-50 via-yellow-50 to-orange-50",
    isSentences: true,
    words: [
      { emoji: "🙋", japanese: "すみません、これはいくらですか？",       romaji: "Sumimasen, kore wa ikura desu ka?",        english: "Excuse me, how much is this?" },
      { emoji: "🛍️", japanese: "これをください。",                       romaji: "Kore wo kudasai.",                         english: "I'll take this one please." },
      { emoji: "💸", japanese: "ちょっと高すぎます。",                   romaji: "Chotto takasugi masu.",                    english: "It's a bit too expensive." },
      { emoji: "🔍", japanese: "もっと安いのはありますか？",             romaji: "Motto yasui no wa arimasu ka?",            english: "Do you have anything cheaper?" },
      { emoji: "💳", japanese: "クレジットカードは使えますか？",         romaji: "Kurejitto kaado wa tsukaemasu ka?",        english: "Can I use a credit card?" },
      { emoji: "🏧", japanese: "レジはどこですか？",                     romaji: "Reji wa doko desu ka?",                    english: "Where is the cashier?" },
      { emoji: "🛒", japanese: "袋に入れてください。",                   romaji: "Fukuro ni irete kudasai.",                 english: "Please put it in a bag." },
      { emoji: "🧾", japanese: "レシートをください。",                   romaji: "Reshiito wo kudasai.",                     english: "Please give me a receipt." },
      { emoji: "📅", japanese: "セールはいつですか？",                   romaji: "Seeru wa itsu desu ka?",                   english: "When is the sale?" },
      { emoji: "👗", japanese: "試着してもいいですか？",                 romaji: "Shichaku shite mo ii desu ka?",            english: "May I try it on?" },
      { emoji: "📦", japanese: "これはどこにありますか？",               romaji: "Kore wa doko ni arimasu ka?",              english: "Where can I find this?" },
      { emoji: "🔄", japanese: "返品できますか？",                       romaji: "Henpin dekimasu ka?",                      english: "Can I return this?" },
      { emoji: "🎁", japanese: "プレゼント用に包んでもらえますか？",     romaji: "Purezento you ni tsutsunde moraemasu ka?", english: "Can you gift wrap it?" },
      { emoji: "✅", japanese: "ありがとうございました。またきます。",   romaji: "Arigatou gozaimashita. Mata kimasu.",       english: "Thank you. I'll come again!" },
    ],
  },
  {
    id: "cashier",
    label: "お支払い",
    icon: "🏧",
    activeColor: "#0ea5e9",
    borderHex: "#7dd3fc",
    bg: "from-sky-50 via-cyan-50 to-blue-50",
    isSentences: true,
    words: [
      { emoji: "🏪", japanese: "いらっしゃいませ。",                         romaji: "Irasshaimase.",                             english: "Welcome! (said by staff)" },
      { emoji: "💴", japanese: "〇〇円になります。",                         romaji: "〇〇-en ni narimasu.",                      english: "That will be XX yen." },
      { emoji: "💳", japanese: "お支払いはどうなさいますか？",               romaji: "Oshiharai wa dou nasaimasu ka?",            english: "How would you like to pay?" },
      { emoji: "💵", japanese: "現金でお願いします。",                       romaji: "Genkin de onegaishimasu.",                  english: "Cash please." },
      { emoji: "💳", japanese: "カードで払います。",                         romaji: "Kaado de haraimasu.",                       english: "I'll pay by card." },
      { emoji: "📱", japanese: "スマホ払いでお願いします。",                 romaji: "Sumaho barai de onegaishimasu.",            english: "I'll pay by smartphone." },
      { emoji: "🎁", japanese: "ポイントカードはお持ちですか？",             romaji: "Pointo kaado wa omochi desu ka?",           english: "Do you have a points card?" },
      { emoji: "🛍️", japanese: "袋はご利用ですか？",                         romaji: "Fukuro wa goriyou desu ka?",                english: "Would you like a bag?" },
      { emoji: "🙅", japanese: "袋はいりません。",                           romaji: "Fukuro wa irimasen.",                       english: "No bag needed, thank you." },
      { emoji: "💰", japanese: "お釣りです。",                               romaji: "Otsuri desu.",                              english: "Here is your change." },
      { emoji: "🧾", japanese: "レシートはご利用ですか？",                   romaji: "Reshiito wa goriyou desu ka?",              english: "Would you like a receipt?" },
      { emoji: "⏳", japanese: "少々お待ちください。",                       romaji: "Shoushou omachi kudasai.",                  english: "Please wait a moment." },
      { emoji: "✅", japanese: "ありがとうございました。",                   romaji: "Arigatou gozaimashita.",                    english: "Thank you very much." },
      { emoji: "🙏", japanese: "またのご来店をお待ちしております。",         romaji: "Mata no goraiten wo omachi shite orimasu.", english: "We look forward to your next visit." },
    ],
  },
  {
    id: "classroom-daily",
    label: "授業の言葉",
    icon: "🎓",
    activeColor: "#6366f1",
    borderHex: "#a5b4fc",
    bg: "from-indigo-50 via-violet-50 to-purple-50",
    isSentences: true,
    words: [
      { emoji: "🧍", japanese: "起立！",                                 romaji: "Kiritsu!",                                   english: "Stand up!" },
      { emoji: "🙇", japanese: "礼！",                                   romaji: "Rei!",                                       english: "Bow!" },
      { emoji: "🪑", japanese: "着席！",                                 romaji: "Chakuseki!",                                 english: "Sit down!" },
      { emoji: "📋", japanese: "出席を取ります。",                       romaji: "Shusseki wo torimasu.",                       english: "I'll take attendance." },
      { emoji: "🙋", japanese: "はい、います。",                         romaji: "Hai, imasu.",                                 english: "Yes, I'm here. (Present)" },
      { emoji: "📖", japanese: "教科書の〇〇ページを開いてください。",   romaji: "Kyoukasho no XX peeji wo hiraite kudasai.",   english: "Please open your textbook to page XX." },
      { emoji: "✏️", japanese: "ノートに書いてください。",               romaji: "Nooto ni kaite kudasai.",                     english: "Please write in your notebook." },
      { emoji: "📝", japanese: "宿題を出してください。",                 romaji: "Shukudai wo dashite kudasai.",                english: "Please hand in your homework." },
      { emoji: "🤚", japanese: "先生、質問があります。",                 romaji: "Sensei, shitsumon ga arimasu.",               english: "Teacher, I have a question." },
      { emoji: "🚽", japanese: "トイレに行ってもいいですか？",           romaji: "Toire ni itte mo ii desu ka?",                english: "May I go to the bathroom?" },
      { emoji: "✅", japanese: "わかりました。",                         romaji: "Wakarimashita.",                             english: "I understand." },
      { emoji: "❓", japanese: "わかりません。",                         romaji: "Wakarimasen.",                               english: "I don't understand." },
      { emoji: "🔁", japanese: "もう一度言ってください。",               romaji: "Mou ichido itte kudasai.",                    english: "Please say it again." },
      { emoji: "🤫", japanese: "静かにしてください。",                   romaji: "Shizuka ni shite kudasai.",                   english: "Please be quiet." },
      { emoji: "👥", japanese: "ペアになってください。",                 romaji: "Pea ni natte kudasai.",                       english: "Please get into pairs." },
      { emoji: "🗣️", japanese: "日本語で話してください。",               romaji: "Nihongo de hanashite kudasai.",               english: "Please speak in Japanese." },
      { emoji: "🔔", japanese: "今日の授業はここまでです。",             romaji: "Kyou no jugyou wa koko made desu.",           english: "That's all for today's class." },
      { emoji: "🏠", japanese: "気をつけて帰ってください。",             romaji: "Ki wo tsukete kaette kudasai.",                english: "Please go home safely." },
    ],
  },
];
